### ISSUE TITLE
INVALID_KEY: Namespace keys can not contain the character "."

### ISSUE THREAD

**Issue by pmarxbraun** [HPouyanmehr/next-intl-split#1]
Hi there, I'm running into an issue when installing the package.

My messages folder structure

![Screenshot 2024-08-30 at 11 34 57](https://github.com/user-attachments/assets/5c469eae-3884-4886-a9fa-1d3e8a9f0df2)

When I import translations in my Header component

```
const t = useTranslations('home')
 return (
        <h1>{t('hero.title')}</h1>
```

`home.hero.title` gets printed even though the JSON is well structured and the key exists.

I got this error :
```
IntlError: INVALID_KEY: Namespace keys can not contain the character "." as this is used to express nesting. Please remove it or replace it with another character.
Invalid keys: home/index.json, shared/header/index.json
```

When logging messages

```
const messages = await getMessages()
console.log('🚀 ~ messages:', messages)
```
it outputs
```
{
  'home/index.json': {
    hero: {
      title: 'Simply the best event platform on the market',
      subtitle: 'Boost your events with a modular solution that simplifies your organization, increases participant engagement tenfold and opens up new horizons.',
      bulletPoints: [Array],
      cta: [Array],
      image_desktop: 'assets/events_en.jpeg',
      image_mobile: 'assets/events_mobile_en.png'
    },
    bentogrid: {
      title: 'Reinvent your events with unique and memorable experiences!',
      solutions: [Array]
    },
    event_type: {
      label: 'Professional events',
      title: 'Make every event a success, whatever the format',
      description: 'Organize impeccable events with our flexible and ergonomic solution, adapted to all your business needs.',
      events: [Array]
    },
    event_format: [ [Object], [Object], [Object] ]
  },
  'shared/header/index.json': {
    links: [ [Object], [Object], [Object], [Object] ],
    login: { title: 'Login', slug: 'https://app.wechain.eu' },
    contact: { title: 'Contact us', slug: '/en/contact' },
    callsToAction: [ [Object], [Object], [Object] ]
  }
}
```
Indeed the keys corresponding to folders are not valid. 
Am I doing something wrong?
Tx

**Comment by HPouyanmehr** [comment]
Hey @pmarxbraun, Thank for reporting this issue.

No, you're doing right. 
The issue comes from the separator character of the package which can be different depends on the OS. (I used `\\` for splitting which is a valid separator only on windows). 

I've fixed the issue and you can update to [v1.0.2](https://github.com/HPouyanmehr/next-intl-split/releases/tag/v1.0.2).
https://github.com/HPouyanmehr/next-intl-split/blob/10141cec12520ad1c090a9a826dd09b1c910e151/package/src/loader.ts#L62

Feel free to reopen the issue if it still remains.
