### ISSUE TITLE
How can I integrate this with Typescript

### ISSUE THREAD

**Issue by brandanking-decently** [HPouyanmehr/next-intl-split#3]
Hi, I was wondering how I can get this to also work with typescript. This package looks great but it would also be good to get this working with types.

**Comment by Megaemce** [comment]
Same here, the type annotation is missing to make it work correctly. 

````ts
Cannot find module 'next-intl-split/loader' or its corresponding type declarations.ts(2307)
````

EDIT: Actually it's a typo in the doc in README, the import should be `load` not `loader`

````ts
import { loadI18nTranslations } from "next-intl-split/load";
````

**Comment by HPouyanmehr** [comment]
Hi @brandanking-decently , I'm sorry about the delay in answering. 

The package is written in typescript, so I think I couldn't understand your point well. Is there any type that you think should be exported from the package? It would be great if you could explain that more specifically.

**Comment by HPouyanmehr** [comment]
Hi @Megaemce, 

Thanks for your point. I did fix that in the README file.

**Comment by brandanking-decently** [comment]
Hi @HPouyanmehr sorry for not explaining this well enough. What I mean is with next intl single file I can use https://next-intl.dev/docs/workflows/typescript which gives type errors etc. Is this possible with this extension?

**Comment by HPouyanmehr** [comment]
Thanks for the clarification @brandanking-decently,

Unfortunately, it is not as easy as the `next-intl` solution (But generally possible). 

The way `next-intl` handles that is to import a **single** JSON file containing all possible keys. Using this method, TypeScript can understand the type of the entire JSON. 
But, as you may know, using `next-intl-split`, you'll store translations into multiple files (with as many as folders you need), and therefore TypeScript can't find keys and their relation, this lead to typing it as `any`.

You cannot also try to type the result of `loadI18nTranslations('path', 'en')` as this method uses `JSON.parse()` and the result of parsed JSON isn't clear for typescript. (I hoped the issue could be resolved with this method, but didn't work:))

BY THE WAY, It is good to know that you can type the messages, but a bit manually. It can be tedious but if you do this as your code grows, you'll have the type benefits as well.

To do it manually:
1. Assume this is my folder and messages structure

```
// /src
└── message
    // English
    ├── en
    |   ├── home
    |   |   └── hero
    |   |       ├── buttons
    |   |       |   └── index.json
    |   |       └── index.json
    ...
```

2. Inside the `global.d.ts` you can do this:
```ts
import enHomeHero from './messages/en/home/hero/index.json';
import enHomeHeroButton from './messages/en/home/hero/buttons/index.json';

type EnHomeHero = typeof enHomeHero;
type EnHomeHeroButton = typeof enHomeHeroButton;

declare global {
  interface IntlMessages {
    home: {
      hero: {
        buttons: EnHomeHeroButton;
      } & EnHomeHero
    }
  }
}
```
The manual part is to add `home` and `hero` keys here in proper relation.

I'm going to close this issue, but feel free to reply or comment if there is a question or idea!

**Comment by brandanking-decently** [comment]
My idea, but I haven't had time to try it was if there was a built in command within the package that would generate a translations.d.ts file that would automatically create the types. Removing the manual part of it. Is this something that you think could be valid within the package?

**Comment by HPouyanmehr** [comment]
I think this can be achievable, as I merge messages if they are in the build process (`production` mode). I can add a property to the `createNextIntlSplitPlugin` that allows user to optionally enable merge in `development` mode as well. 

I didn't do this by default because the merge process includes loading (looping through paths) and writing to a new file, which may slow things down in some situations.

I'll try to give it a shot. Thanks for sharing your thoughts.

**Comment by HPouyanmehr** [comment]
Hi @brandanking-decently,

From `v1.2.4`, You can have the type check. Visit [this section](https://github.com/HPouyanmehr/next-intl-split?tab=readme-ov-file#add-support-for-typescript) for enabling it.
